### PR TITLE
Thommy Update

### PR DESCRIPTION
**Pull request by ThommyDude**
Look, a large update for the save editor!

Changed a whole bunch of stuff.
Read commit notes about WHAT I have done.
I might look into character levels/EXP and/or stats at some point but I really don't know that much about how the reading from the byte file works, so I'm unsure.

TL;DR:
Changed the layout and added the ability to change lvls/unlock specific jobs!
CSS definitly needs some work because I am terrible at making things look... acceptable.
Maybe more to come, but probably now?

### CODE REVIEW

**Comment by Soaprman** [comment]
Nice! I do have a few small changes I'd like you to make before I merge this.

* Please use "Unlocked" instead of "Unlkd". In general, it's best not to abbreviate words unless the full name is particularly cumbersome.
* Use a more specific suffix than "_button" for the +1 buttons. This makes things more clear and also makes it so you don't get unwanted results if you CTRL+F the suffix (as it is a substring of the other suffixes).

Your styling looks fine, by the way. Maybe on other fancy-pants sites it might look less than acceptable, but I'm not looking to win any web design awards here. :)

Everything else looks good, so once you push a commit with those changes I'll merge it in.

**Comment by ThommyDude** [comment]
> * Please use "Unlocked" instead of "Unlkd". In general, it's best not to abbreviate words unless the full name is particularly cumbersome.
> * Use a more specific suffix than "_button" for the +1 buttons. This makes things more clear and also makes it so you don't get unwanted results if you CTRL+F the suffix (as it is a substring of the other suffixes).

This first one is easy to fix and I'll get on that  when I have time.

The second one is gonna be slightly more annoying to **_fix_** simply because my code is looking for that specific part to attach the event handler to.
And the real reason it's _hard_ to fix is because I am terrible at naming things. I'm the kinda guy who names half his variables herp, derp or some other variation of those.

- [x] Fix unnecessary abbreviations.
- [x] Fix unspecific suffixes.

**Comment by ThommyDude** [comment]
There we go.
Now the only thing I really still want to do is PG and CP to try and understand how the byte reading/writing works so that at some point I might be able to get stats such as current/max HP/MP and Level/Exp.
But I just really don't get how it works... Could you help with that? If you want and have the time, otherwise I'll try to just screw around with it myself and either get it working or I'll just give up on it at one point.

**Comment by Soaprman** [comment]
Thanks! I'll hit you up on gbatemp about the rest.

**Pull request merged**
